# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Vectorization" data-toc-modified-id="Vectorization-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Vectorization</a></div><div class="lev1 toc-item"><a href="#Vectorizing-Logistic-Regression" data-toc-modified-id="Vectorizing-Logistic-Regression-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Vectorizing Logistic Regression</a></div><div class="lev1 toc-item"><a href="#Vectorizing-Logistic-Regression's-Gradient-Output" data-toc-modified-id="Vectorizing-Logistic-Regression's-Gradient-Output-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Vectorizing Logistic Regression's Gradient Output</a></div><div class="lev1 toc-item"><a href="#A-note-on-python/numpy-vectors" data-toc-modified-id="A-note-on-python/numpy-vectors-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>A note on python/numpy vectors</a></div>

# Vectorization
![](https://i.imgur.com/yz60bns.png)

In [1]:
import numpy as np

In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)


In [3]:
%time c = np.dot(a, b)

CPU times: user 1.62 ms, sys: 727 µs, total: 2.34 ms
Wall time: 1.06 ms


In [4]:
def loop():
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]

In [5]:
%time loop()

CPU times: user 316 ms, sys: 2.56 ms, total: 319 ms
Wall time: 317 ms


![](https://i.imgur.com/p94lp3F.png)

![](https://i.imgur.com/62FCVzX.png)

![](https://i.imgur.com/lQnsLDn.png)

# Vectorizing Logistic Regression


![](https://i.imgur.com/3NO1maQ.png)

# Vectorizing Logistic Regression's Gradient Output

![](https://i.imgur.com/5HLkUab.png)

# A note on python/numpy vectors

In [6]:
a = np.random.randn(5)
a

array([-0.91796822, -0.53903443,  1.00289266,  0.22272871, -0.35617949])

In [7]:
a.shape

(5,)

In [8]:
a.T

array([-0.91796822, -0.53903443,  1.00289266,  0.22272871, -0.35617949])

In [9]:
np.dot(a, a.T)

2.3154893533786054

In [10]:
a = np.random.randn(5, 1)
a

array([[-1.26834861],
       [-0.254855  ],
       [-1.37786229],
       [ 0.18718574],
       [-1.31341244]])

In [11]:
a.shape

(5, 1)

In [12]:
a.T

array([[-1.26834861, -0.254855  , -1.37786229,  0.18718574, -1.31341244]])

In [13]:
np.dot(a, a.T)

array([[ 1.60870819,  0.32324498,  1.74760972, -0.23741677,  1.66586484],
       [ 0.32324498,  0.06495107,  0.35115509, -0.04770522,  0.33472972],
       [ 1.74760972,  0.35115509,  1.8985045 , -0.25791618,  1.80970147],
       [-0.23741677, -0.04770522, -0.25791618,  0.0350385 , -0.24585208],
       [ 1.66586484,  0.33472972,  1.80970147, -0.24585208,  1.72505223]])

![](https://i.imgur.com/RWHkYsw.png)

In [14]:
%load_ext version_information
%version_information numpy

Software versions
Python 3.6.6 64bit [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
IPython 7.0.1
OS Darwin 17.7.0 x86_64 i386 64bit
numpy 1.15.1
Sun Oct 14 19:41:16 2018 MDT